use ::libc;

pub mod q_shared_h {

    //=========================================================
    // bit field limits
    // playerState_t is the information needed by both the client and server
    // to predict player motion and actions
    // nothing outside of pmove should modify these, or some degree of prediction error
    // will occur
    // you can't add anything to this without modifying the code in msg.c
    // playerState_t is a full superset of entityState_t as it is used by players,
    // so if a playerState_t is transmitted, the entityState_t can be fully derived
    // from it.

    //====================================================================
    //
    // usercmd_t->button bits, many of which are generated by the client system,
    // so they aren't game/cgame only definitions
    //
    // displays talk balloon and disables actions
    // walking can't just be inferred from MOVE_RUN
    // because a key pressed late in the frame will
    // only generate a small move value for that frame
    // walking will use different animations and
    // won't generate footsteps
    // any key whatsoever
    // if forwardmove or rightmove are >= MOVE_RUN,
    // then BUTTON_WALKING should be set
    // usercmd_t is sent to the server each client frame

    //===================================================================
    // if entityState->solid == SOLID_BMODEL, modelindex is an inline model number

    // value = base + sin( time / duration ) * delta

    // non-parametric, but interpolate between snapshots

    // entityState_t is the information conveyed from the server
    // in an update message about entities that the client will
    // need to render in some way
    // Different eTypes may use the information in different ways
    // The messages are delta compressed, so it doesn't really matter if
    // the structure size is fairly large

    #[inline]

    pub unsafe extern "C" fn VectorLengthSquared(
        mut v: *const crate::src::qcommon::q_shared::vec_t,
    ) -> crate::src::qcommon::q_shared::vec_t {
        return *v.offset(0 as i32 as isize) * *v.offset(0 as i32 as isize)
            + *v.offset(1 as i32 as isize) * *v.offset(1 as i32 as isize)
            + *v.offset(2 as i32 as isize) * *v.offset(2 as i32 as isize);
    }

    // __Q_SHARED_H
}

pub use crate::stddef_h::size_t;

pub use crate::be_aas_h::C2RustUnnamed_0;
pub use crate::g_public_h::entityShared_t;
pub use crate::g_public_h::sharedEntity_t;
pub use crate::qcommon_h::msg_t;
pub use crate::qcommon_h::netadr_t;
pub use crate::qcommon_h::netadrtype_t;
pub use crate::qcommon_h::netchan_t;
pub use crate::qcommon_h::netsrc_t;
pub use crate::qcommon_h::svc_EOF;
pub use crate::qcommon_h::svc_bad;
pub use crate::qcommon_h::svc_baseline;
pub use crate::qcommon_h::svc_configstring;
pub use crate::qcommon_h::svc_download;
pub use crate::qcommon_h::svc_gamestate;
pub use crate::qcommon_h::svc_nop;
pub use crate::qcommon_h::svc_ops_e;
pub use crate::qcommon_h::svc_serverCommand;
pub use crate::qcommon_h::svc_snapshot;
pub use crate::qcommon_h::svc_voipOpus;
pub use crate::qcommon_h::svc_voipSpeex;
pub use crate::qcommon_h::NA_BAD;
pub use crate::qcommon_h::NA_BOT;
pub use crate::qcommon_h::NA_BROADCAST;
pub use crate::qcommon_h::NA_IP;
pub use crate::qcommon_h::NA_IP6;
pub use crate::qcommon_h::NA_LOOPBACK;
pub use crate::qcommon_h::NA_MULTICAST6;
pub use crate::qcommon_h::NA_UNSPEC;
pub use crate::qcommon_h::NS_CLIENT;
pub use crate::qcommon_h::NS_SERVER;
pub use crate::server_h::challenge_t;
pub use crate::server_h::clientSnapshot_t;
pub use crate::server_h::clientState_t;
pub use crate::server_h::client_s;
pub use crate::server_h::client_t;
pub use crate::server_h::netchan_buffer_s;
pub use crate::server_h::netchan_buffer_t;
pub use crate::server_h::serverState_t;
pub use crate::server_h::serverStatic_t;
pub use crate::server_h::server_t;
pub use crate::server_h::svEntity_s;
pub use crate::server_h::svEntity_t;
pub use crate::server_h::voipServerPacket_s;
pub use crate::server_h::voipServerPacket_t;
pub use crate::server_h::worldSector_s;
pub use crate::server_h::CS_ACTIVE;
pub use crate::server_h::CS_CONNECTED;
pub use crate::server_h::CS_FREE;
pub use crate::server_h::CS_PRIMED;
pub use crate::server_h::CS_ZOMBIE;
pub use crate::server_h::SS_DEAD;
pub use crate::server_h::SS_GAME;
pub use crate::server_h::SS_LOADING;

pub use crate::src::qcommon::common::com_timescale;
pub use crate::src::qcommon::common::Com_DPrintf;
pub use crate::src::qcommon::common::Com_Error;
pub use crate::src::qcommon::common::Com_Printf;
pub use crate::src::qcommon::common::Z_Free;
pub use crate::src::qcommon::msg::MSG_Clear;
pub use crate::src::qcommon::msg::MSG_Init;
pub use crate::src::qcommon::msg::MSG_WriteBits;
pub use crate::src::qcommon::msg::MSG_WriteByte;
pub use crate::src::qcommon::msg::MSG_WriteData;
pub use crate::src::qcommon::msg::MSG_WriteDeltaEntity;
pub use crate::src::qcommon::msg::MSG_WriteDeltaPlayerstate;
pub use crate::src::qcommon::msg::MSG_WriteLong;
pub use crate::src::qcommon::msg::MSG_WriteShort;
pub use crate::src::qcommon::msg::MSG_WriteString;
pub use crate::src::qcommon::net_ip::Sys_IsLANAddress;
pub use crate::src::qcommon::q_shared::byte;
pub use crate::src::qcommon::q_shared::cvar_s;
pub use crate::src::qcommon::q_shared::cvar_t;
pub use crate::src::qcommon::q_shared::entityState_s;
pub use crate::src::qcommon::q_shared::entityState_t;
pub use crate::src::qcommon::q_shared::fileHandle_t;
pub use crate::src::qcommon::q_shared::playerState_s;
pub use crate::src::qcommon::q_shared::playerState_t;
pub use crate::src::qcommon::q_shared::qboolean;
pub use crate::src::qcommon::q_shared::qfalse;
pub use crate::src::qcommon::q_shared::qtrue;
pub use crate::src::qcommon::q_shared::trType_t;
pub use crate::src::qcommon::q_shared::trajectory_t;
pub use crate::src::qcommon::q_shared::usercmd_s;
pub use crate::src::qcommon::q_shared::usercmd_t;
pub use crate::src::qcommon::q_shared::vec3_t;
pub use crate::src::qcommon::q_shared::vec_t;
pub use crate::src::qcommon::q_shared::ERR_DISCONNECT;
pub use crate::src::qcommon::q_shared::ERR_DROP;
pub use crate::src::qcommon::q_shared::ERR_FATAL;
pub use crate::src::qcommon::q_shared::ERR_NEED_CD;
pub use crate::src::qcommon::q_shared::ERR_SERVERDISCONNECT;
pub use crate::src::qcommon::q_shared::TR_GRAVITY;
pub use crate::src::qcommon::q_shared::TR_INTERPOLATE;
pub use crate::src::qcommon::q_shared::TR_LINEAR;
pub use crate::src::qcommon::q_shared::TR_LINEAR_STOP;
pub use crate::src::qcommon::q_shared::TR_SINE;
pub use crate::src::qcommon::q_shared::TR_STATIONARY;
pub use crate::src::server::sv_game::SV_GameClientNum;
pub use crate::src::server::sv_game::SV_GentityNum;
pub use crate::src::server::sv_game::SV_SvEntityForGentity;
pub use crate::src::server::sv_main::sv;
pub use crate::src::server::sv_main::sv_lanForceRate;
pub use crate::src::server::sv_main::sv_maxclients;
pub use crate::src::server::sv_main::sv_padPackets;
pub use crate::src::server::sv_main::svs;
pub use crate::src::server::sv_main::SV_RateMsec;
pub use crate::src::server::sv_net_chan::SV_Netchan_Transmit;
pub use crate::src::server::sv_snapshot::q_shared_h::VectorLengthSquared;
pub use crate::stdlib::__compar_fn_t;

pub use crate::stdlib::qsort;

#[repr(C)]
#[derive(Copy, Clone)]
pub struct snapshotEntityNumbers_t {
    pub numSnapshotEntities: i32,
    pub snapshotEntities: [i32; 256],
}
/*
===========================================================================
Copyright (C) 1999-2005 Id Software, Inc.

This file is part of Quake III Arena source code.

Quake III Arena source code is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

Quake III Arena source code is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Quake III Arena source code; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
===========================================================================
*/
/*
=============================================================================

Delta encode a client frame onto the network channel

A normal server packet will look like:

4	sequence number (high bit set if an oversize fragment)
<optional reliable commands>
1	svc_snapshot
4	last client reliable command
4	serverTime
1	lastframe for delta compression
1	snapFlags
1	areaBytes
<areabytes>
<playerstate>
<packetentities>

=============================================================================
*/
/*
=============
SV_EmitPacketEntities

Writes a delta update of an entityState_t list to the message.
=============
*/

unsafe extern "C" fn SV_EmitPacketEntities(
    mut from: *mut crate::server_h::clientSnapshot_t,
    mut to: *mut crate::server_h::clientSnapshot_t,
    mut msg: *mut crate::qcommon_h::msg_t,
) {
    let mut oldent: *mut crate::src::qcommon::q_shared::entityState_t =
        0 as *mut crate::src::qcommon::q_shared::entityState_t;
    let mut newent: *mut crate::src::qcommon::q_shared::entityState_t =
        0 as *mut crate::src::qcommon::q_shared::entityState_t;
    let mut oldindex: i32 = 0;
    let mut newindex: i32 = 0;
    let mut oldnum: i32 = 0;
    let mut newnum: i32 = 0;
    let mut from_num_entities: i32 = 0;
    // generate the delta update
    if from.is_null() {
        from_num_entities = 0 as i32
    } else {
        from_num_entities = (*from).num_entities
    }
    newent = 0 as *mut crate::src::qcommon::q_shared::entityState_t;
    oldent = 0 as *mut crate::src::qcommon::q_shared::entityState_t;
    newindex = 0 as i32;
    oldindex = 0 as i32;
    while newindex < (*to).num_entities || oldindex < from_num_entities {
        if newindex >= (*to).num_entities {
            newnum = 9999 as i32
        } else {
            newent = &mut *crate::src::server::sv_main::svs.snapshotEntities.offset(
                (((*to).first_entity + newindex)
                    % crate::src::server::sv_main::svs.numSnapshotEntities)
                    as isize,
            ) as *mut crate::src::qcommon::q_shared::entityState_t;
            newnum = (*newent).number
        }
        if oldindex >= from_num_entities {
            oldnum = 9999 as i32
        } else {
            oldent = &mut *crate::src::server::sv_main::svs.snapshotEntities.offset(
                (((*from).first_entity + oldindex)
                    % crate::src::server::sv_main::svs.numSnapshotEntities)
                    as isize,
            ) as *mut crate::src::qcommon::q_shared::entityState_t;
            oldnum = (*oldent).number
        }
        if newnum == oldnum {
            // delta update from old position
            // because the force parm is qfalse, this will not result
            // in any bytes being emitted if the entity has not changed at all
            crate::src::qcommon::msg::MSG_WriteDeltaEntity(
                msg as *mut crate::qcommon_h::msg_t,
                oldent as *mut crate::src::qcommon::q_shared::entityState_s,
                newent as *mut crate::src::qcommon::q_shared::entityState_s,
                crate::src::qcommon::q_shared::qfalse,
            );
            oldindex += 1;
            newindex += 1
        } else if newnum < oldnum {
            // this is a new entity, send it from the baseline
            crate::src::qcommon::msg::MSG_WriteDeltaEntity(
                msg as *mut crate::qcommon_h::msg_t,
                &mut (*crate::src::server::sv_main::sv
                    .svEntities
                    .as_mut_ptr()
                    .offset(newnum as isize))
                .baseline as *mut _
                    as *mut crate::src::qcommon::q_shared::entityState_s,
                newent as *mut crate::src::qcommon::q_shared::entityState_s,
                crate::src::qcommon::q_shared::qtrue,
            );
            newindex += 1
        } else {
            if !(newnum > oldnum) {
                continue;
            }
            // the old entity isn't present in the new message
            crate::src::qcommon::msg::MSG_WriteDeltaEntity(
                msg as *mut crate::qcommon_h::msg_t,
                oldent as *mut crate::src::qcommon::q_shared::entityState_s,
                0 as *mut crate::src::qcommon::q_shared::entityState_s
                    as *mut crate::src::qcommon::q_shared::entityState_s,
                crate::src::qcommon::q_shared::qtrue,
            );
            oldindex += 1
        }
    }
    crate::src::qcommon::msg::MSG_WriteBits(
        msg as *mut crate::qcommon_h::msg_t,
        ((1 as i32) << 10 as i32) - 1 as i32,
        10 as i32,
    );
    // end of packetentities
}
/*
==================
SV_WriteSnapshotToClient
==================
*/

unsafe extern "C" fn SV_WriteSnapshotToClient(
    mut client: *mut crate::server_h::client_t,
    mut msg: *mut crate::qcommon_h::msg_t,
) {
    let mut frame: *mut crate::server_h::clientSnapshot_t =
        0 as *mut crate::server_h::clientSnapshot_t;
    let mut oldframe: *mut crate::server_h::clientSnapshot_t =
        0 as *mut crate::server_h::clientSnapshot_t;
    let mut lastframe: i32 = 0;
    let mut i: i32 = 0;
    let mut snapFlags: i32 = 0;
    // this is the snapshot we are creating
    frame = &mut *(*client)
        .frames
        .as_mut_ptr()
        .offset(((*client).netchan.outgoingSequence & 32 as i32 - 1 as i32) as isize)
        as *mut crate::server_h::clientSnapshot_t;
    // try to use a previous frame as the source for delta compressing the snapshot
    if (*client).deltaMessage <= 0 as i32
        || (*client).state as u32 != crate::server_h::CS_ACTIVE as i32 as u32
    {
        // client is asking for a retransmit
        oldframe = 0 as *mut crate::server_h::clientSnapshot_t;
        lastframe = 0 as i32
    } else if (*client).netchan.outgoingSequence - (*client).deltaMessage >= 32 as i32 - 3 as i32 {
        // client hasn't gotten a good message through in a long time
        crate::src::qcommon::common::Com_DPrintf(
            b"%s: Delta request from out of date packet.\n\x00" as *const u8 as *const libc::c_char,
            (*client).name.as_mut_ptr(),
        );
        oldframe = 0 as *mut crate::server_h::clientSnapshot_t;
        lastframe = 0 as i32
    } else {
        // we have a valid snapshot to delta from
        oldframe = &mut *(*client)
            .frames
            .as_mut_ptr()
            .offset(((*client).deltaMessage & 32 as i32 - 1 as i32) as isize)
            as *mut crate::server_h::clientSnapshot_t;
        lastframe = (*client).netchan.outgoingSequence - (*client).deltaMessage;
        // the snapshot's entities may still have rolled off the buffer, though
        if (*oldframe).first_entity
            <= crate::src::server::sv_main::svs.nextSnapshotEntities
                - crate::src::server::sv_main::svs.numSnapshotEntities
        {
            crate::src::qcommon::common::Com_DPrintf(
                b"%s: Delta request from out of date entities.\n\x00" as *const u8
                    as *const libc::c_char,
                (*client).name.as_mut_ptr(),
            );
            oldframe = 0 as *mut crate::server_h::clientSnapshot_t;
            lastframe = 0 as i32
        }
    }
    crate::src::qcommon::msg::MSG_WriteByte(
        msg as *mut crate::qcommon_h::msg_t,
        crate::qcommon_h::svc_snapshot as i32,
    );
    // NOTE, MRE: now sent at the start of every message from server to client
    // let the client know which reliable clientCommands we have received
    //MSG_WriteLong( msg, client->lastClientCommand );
    // send over the current server time so the client can drift
    // its view of time to try to match
    if (*client).oldServerTime != 0 {
        // The server has not yet got an acknowledgement of the
        // new gamestate from this client, so continue to send it
        // a time as if the server has not restarted. Note from
        // the client's perspective this time is strictly speaking
        // incorrect, but since it'll be busy loading a map at
        // the time it doesn't really matter.
        crate::src::qcommon::msg::MSG_WriteLong(
            msg as *mut crate::qcommon_h::msg_t,
            crate::src::server::sv_main::sv.time + (*client).oldServerTime,
        );
    } else {
        crate::src::qcommon::msg::MSG_WriteLong(
            msg as *mut crate::qcommon_h::msg_t,
            crate::src::server::sv_main::sv.time,
        );
    }
    // what we are delta'ing from
    crate::src::qcommon::msg::MSG_WriteByte(msg as *mut crate::qcommon_h::msg_t, lastframe);
    snapFlags = crate::src::server::sv_main::svs.snapFlagServerBit;
    if (*client).rateDelayed as u64 != 0 {
        snapFlags |= 1 as i32
    }
    if (*client).state as u32 != crate::server_h::CS_ACTIVE as i32 as u32 {
        snapFlags |= 2 as i32
    }
    crate::src::qcommon::msg::MSG_WriteByte(msg as *mut crate::qcommon_h::msg_t, snapFlags);
    // send over the areabits
    crate::src::qcommon::msg::MSG_WriteByte(
        msg as *mut crate::qcommon_h::msg_t,
        (*frame).areabytes,
    );
    crate::src::qcommon::msg::MSG_WriteData(
        msg as *mut crate::qcommon_h::msg_t,
        (*frame).areabits.as_mut_ptr() as *const libc::c_void,
        (*frame).areabytes,
    );
    // delta encode the playerstate
    if !oldframe.is_null() {
        crate::src::qcommon::msg::MSG_WriteDeltaPlayerstate(
            msg as *mut crate::qcommon_h::msg_t,
            &mut (*oldframe).ps as *mut _ as *mut crate::src::qcommon::q_shared::playerState_s,
            &mut (*frame).ps as *mut _ as *mut crate::src::qcommon::q_shared::playerState_s,
        );
    } else {
        crate::src::qcommon::msg::MSG_WriteDeltaPlayerstate(
            msg as *mut crate::qcommon_h::msg_t,
            0 as *mut crate::src::qcommon::q_shared::playerState_s
                as *mut crate::src::qcommon::q_shared::playerState_s,
            &mut (*frame).ps as *mut _ as *mut crate::src::qcommon::q_shared::playerState_s,
        );
    }
    // delta encode the entities
    SV_EmitPacketEntities(oldframe, frame, msg);
    // padding for rate debugging
    if (*crate::src::server::sv_main::sv_padPackets).integer != 0 {
        i = 0 as i32;
        while i < (*crate::src::server::sv_main::sv_padPackets).integer {
            crate::src::qcommon::msg::MSG_WriteByte(
                msg as *mut crate::qcommon_h::msg_t,
                crate::qcommon_h::svc_nop as i32,
            );
            i += 1
        }
    };
}
/*
==================
SV_UpdateServerCommandsToClient

(re)send all server commands the client hasn't acknowledged yet
==================
*/
#[no_mangle]

pub unsafe extern "C" fn SV_UpdateServerCommandsToClient(
    mut client: *mut crate::server_h::client_t,
    mut msg: *mut crate::qcommon_h::msg_t,
) {
    let mut i: i32 = 0;
    // write any unacknowledged serverCommands
    i = (*client).reliableAcknowledge + 1 as i32;
    while i <= (*client).reliableSequence {
        crate::src::qcommon::msg::MSG_WriteByte(
            msg as *mut crate::qcommon_h::msg_t,
            crate::qcommon_h::svc_serverCommand as i32,
        );
        crate::src::qcommon::msg::MSG_WriteLong(msg as *mut crate::qcommon_h::msg_t, i);
        crate::src::qcommon::msg::MSG_WriteString(
            msg as *mut crate::qcommon_h::msg_t,
            (*client).reliableCommands[(i & 64 as i32 - 1 as i32) as usize].as_mut_ptr(),
        );
        i += 1
    }
    (*client).reliableSent = (*client).reliableSequence;
}
/*
=======================
SV_QsortEntityNumbers
=======================
*/

unsafe extern "C" fn SV_QsortEntityNumbers(
    mut a: *const libc::c_void,
    mut b: *const libc::c_void,
) -> i32 {
    let mut ea: *mut i32 = 0 as *mut i32;
    let mut eb: *mut i32 = 0 as *mut i32;
    ea = a as *mut i32;
    eb = b as *mut i32;
    if *ea == *eb {
        crate::src::qcommon::common::Com_Error(
            crate::src::qcommon::q_shared::ERR_DROP as i32,
            b"SV_QsortEntityStates: duplicated entity\x00" as *const u8 as *const libc::c_char,
        );
    }
    if *ea < *eb {
        return -(1 as i32);
    }
    return 1 as i32;
}
/*
===============
SV_AddEntToSnapshot
===============
*/

unsafe extern "C" fn SV_AddEntToSnapshot(
    mut svEnt: *mut crate::server_h::svEntity_t,
    mut gEnt: *mut crate::g_public_h::sharedEntity_t,
    mut eNums: *mut snapshotEntityNumbers_t,
) {
    // if we have already added this entity to this snapshot, don't add again
    if (*svEnt).snapshotCounter == crate::src::server::sv_main::sv.snapshotCounter {
        return;
    }
    (*svEnt).snapshotCounter = crate::src::server::sv_main::sv.snapshotCounter;
    // if we are full, silently discard entities
    if (*eNums).numSnapshotEntities == 256 as i32 {
        return;
    }
    (*eNums).snapshotEntities[(*eNums).numSnapshotEntities as usize] = (*gEnt).s.number;
    (*eNums).numSnapshotEntities += 1;
}
/*
===============
SV_AddEntitiesVisibleFromPoint
===============
*/

unsafe extern "C" fn SV_AddEntitiesVisibleFromPoint(
    mut origin: *mut crate::src::qcommon::q_shared::vec_t,
    mut frame: *mut crate::server_h::clientSnapshot_t,
    mut eNums: *mut snapshotEntityNumbers_t,
    mut _portal: crate::src::qcommon::q_shared::qboolean,
) {
    let mut e: i32 = 0;
    let mut i: i32 = 0;
    let mut ent: *mut crate::g_public_h::sharedEntity_t =
        0 as *mut crate::g_public_h::sharedEntity_t;
    let mut svEnt: *mut crate::server_h::svEntity_t = 0 as *mut crate::server_h::svEntity_t;
    let mut l: i32 = 0;
    let mut clientarea: i32 = 0;
    let mut clientcluster: i32 = 0;
    let mut leafnum: i32 = 0;
    let mut clientpvs: *mut crate::src::qcommon::q_shared::byte =
        0 as *mut crate::src::qcommon::q_shared::byte;
    let mut bitvector: *mut crate::src::qcommon::q_shared::byte =
        0 as *mut crate::src::qcommon::q_shared::byte;
    // during an error shutdown message we may need to transmit
    // the shutdown message after the server has shutdown, so
    // specfically check for it
    if crate::src::server::sv_main::sv.state as u64 == 0 {
        return;
    }
    leafnum = crate::src::qcommon::cm_test::CM_PointLeafnum(
        origin as *const crate::src::qcommon::q_shared::vec_t,
    );
    clientarea = crate::src::qcommon::cm_load::CM_LeafArea(leafnum);
    clientcluster = crate::src::qcommon::cm_load::CM_LeafCluster(leafnum);
    // calculate the visible areas
    (*frame).areabytes =
        crate::src::qcommon::cm_test::CM_WriteAreaBits((*frame).areabits.as_mut_ptr(), clientarea);
    clientpvs = crate::src::qcommon::cm_test::CM_ClusterPVS(clientcluster);
    let mut current_block_26: u64;
    e = 0 as i32;
    while e < crate::src::server::sv_main::sv.num_entities {
        ent =
            crate::src::server::sv_game::SV_GentityNum(e) as *mut crate::g_public_h::sharedEntity_t;
        // never send entities that aren't linked in
        if !((*ent).r.linked as u64 == 0) {
            if (*ent).s.number != e {
                crate::src::qcommon::common::Com_DPrintf(
                    b"FIXING ENT->S.NUMBER!!!\n\x00" as *const u8 as *const libc::c_char,
                );
                (*ent).s.number = e
            }
            // entities can be flagged to explicitly not be sent to the client
            if !((*ent).r.svFlags & 0x1 as i32 != 0) {
                // entities can be flagged to be sent to only one client
                if (*ent).r.svFlags & 0x100 as i32 != 0 {
                    if (*ent).r.singleClient != (*frame).ps.clientNum {
                        current_block_26 = 7651349459974463963;
                    } else {
                        current_block_26 = 13472856163611868459;
                    }
                } else {
                    current_block_26 = 13472856163611868459;
                }
                match current_block_26 {
                    7651349459974463963 => {}
                    _ =>
                    // entities can be flagged to be sent to everyone but one client
                    {
                        if (*ent).r.svFlags & 0x800 as i32 != 0 {
                            if (*ent).r.singleClient == (*frame).ps.clientNum {
                                current_block_26 = 7651349459974463963;
                            } else {
                                current_block_26 = 13550086250199790493;
                            }
                        } else {
                            current_block_26 = 13550086250199790493;
                        }
                        match current_block_26 {
                            7651349459974463963 => {}
                            _ =>
                            // entities can be flagged to be sent to a given mask of clients
                            {
                                if (*ent).r.svFlags & 0x2 as i32 != 0 {
                                    if (*frame).ps.clientNum >= 32 as i32 {
                                        crate::src::qcommon::common::Com_Error(
                                            crate::src::qcommon::q_shared::ERR_DROP as i32,
                                            b"SVF_CLIENTMASK: clientNum >= 32\x00" as *const u8
                                                as *const libc::c_char,
                                        );
                                    }
                                    if !(*ent).r.singleClient & (1 as i32) << (*frame).ps.clientNum
                                        != 0
                                    {
                                        current_block_26 = 7651349459974463963;
                                    } else {
                                        current_block_26 = 652864300344834934;
                                    }
                                } else {
                                    current_block_26 = 652864300344834934;
                                }
                                match current_block_26 {
                                    7651349459974463963 => {}
                                    _ => {
                                        svEnt = crate::src::server::sv_game::SV_SvEntityForGentity(
                                            ent as *mut crate::g_public_h::sharedEntity_t,
                                        )
                                            as *mut crate::server_h::svEntity_s;
                                        // don't double add an entity through portals
                                        if !((*svEnt).snapshotCounter
                                            == crate::src::server::sv_main::sv.snapshotCounter)
                                        {
                                            // broadcast entities are always sent
                                            if (*ent).r.svFlags & 0x20 as i32 != 0 {
                                                SV_AddEntToSnapshot(svEnt, ent, eNums);
                                            } else {
                                                // ignore if not touching a PV leaf
                                                // check area
                                                if crate::src::qcommon::cm_test::CM_AreasConnected(
                                                    clientarea,
                                                    (*svEnt).areanum,
                                                )
                                                    as u64
                                                    == 0
                                                {
                                                    // doors can legally straddle two areas, so
                                                    // we may need to check another one
                                                    if crate::src::qcommon::cm_test::CM_AreasConnected(clientarea,
                                                                         (*svEnt).areanum2)
                                                           as u64 == 0 {
                                                        current_block_26 =
                                                            7651349459974463963;
                                                        // blocked by a door
                                                    } else {
                                                        current_block_26 =
                                                            7427571413727699167;
                                                    }
                                                } else {
                                                    current_block_26 = 7427571413727699167;
                                                }
                                                match current_block_26 {
                                                    7651349459974463963 => {}
                                                    _ => {
                                                        bitvector = clientpvs;
                                                        // check individual leafs
                                                        if !((*svEnt).numClusters == 0) {
                                                            l = 0 as i32;
                                                            i = 0 as i32;
                                                            while i < (*svEnt).numClusters {
                                                                l = (*svEnt).clusternums
                                                                    [i as usize];
                                                                if *bitvector.offset(
                                                                    (l >> 3 as i32) as isize,
                                                                )
                                                                    as i32
                                                                    & (1 as i32) << (l & 7 as i32)
                                                                    != 0
                                                                {
                                                                    break;
                                                                }
                                                                i += 1
                                                            }
                                                            // if we haven't found it to be visible,
                                                            // check overflow clusters that coudln't be stored
                                                            if i == (*svEnt).numClusters {
                                                                if (*svEnt).lastCluster != 0 {
                                                                    while l <= (*svEnt).lastCluster
                                                                    {
                                                                        if *bitvector.offset(
                                                                            (l >> 3 as i32)
                                                                                as isize,
                                                                        )
                                                                            as i32
                                                                            & (1 as i32)
                                                                                << (l & 7 as i32)
                                                                            != 0
                                                                        {
                                                                            break;
                                                                        }
                                                                        l += 1
                                                                    }
                                                                    if l == (*svEnt).lastCluster {
                                                                        current_block_26 =
                                                                            7651349459974463963;
                                                                    } else {
                                                                        current_block_26 =
                                                                            9512719473022792396;
                                                                    }
                                                                } else {
                                                                    current_block_26 =
                                                                        7651349459974463963;
                                                                }
                                                            } else {
                                                                current_block_26 =
                                                                    9512719473022792396;
                                                            }
                                                            match current_block_26 {
                                                                7651349459974463963 => {}
                                                                _ => {
                                                                    // add it
                                                                    SV_AddEntToSnapshot(
                                                                        svEnt, ent, eNums,
                                                                    );
                                                                    // if it's a portal entity, add everything visible from its camera position
                                                                    if (*ent).r.svFlags
                                                                        & 0x40 as i32
                                                                        != 0
                                                                    {
                                                                        if (*ent).s.generic1 != 0 {
                                                                            let mut dir:
                                                                                    crate::src::qcommon::q_shared::vec3_t =
                                                                                [0.;
                                                                                    3];
                                                                            dir[0 as i32
                                                                                as usize] = (*ent)
                                                                                .s
                                                                                .origin
                                                                                [0 as i32 as usize]
                                                                                - *origin.offset(
                                                                                    0 as i32
                                                                                        as isize,
                                                                                );
                                                                            dir[1 as i32
                                                                                as usize] = (*ent)
                                                                                .s
                                                                                .origin
                                                                                [1 as i32 as usize]
                                                                                - *origin.offset(
                                                                                    1 as i32
                                                                                        as isize,
                                                                                );
                                                                            dir[2 as i32
                                                                                as usize] = (*ent)
                                                                                .s
                                                                                .origin
                                                                                [2 as i32 as usize]
                                                                                - *origin.offset(
                                                                                    2 as i32
                                                                                        as isize,
                                                                                );
                                                                            if VectorLengthSquared(dir.as_mut_ptr()
                                                                                                       as
                                                                                                       *const crate::src::qcommon::q_shared::vec_t)
                                                                                   >
                                                                                   (*ent).s.generic1
                                                                                       as
                                                                                       f32
                                                                                       *
                                                                                       (*ent).s.generic1
                                                                                           as
                                                                                           f32
                                                                               {
                                                                                current_block_26
                                                                                    =
                                                                                    7651349459974463963;
                                                                            } else {
                                                                                current_block_26
                                                                                    =
                                                                                    8869332144787829186;
                                                                            }
                                                                        } else {
                                                                            current_block_26 =
                                                                                8869332144787829186;
                                                                        }
                                                                        match current_block_26 {
                                                                            7651349459974463963 => {
                                                                            }
                                                                            _ => {
                                                                                SV_AddEntitiesVisibleFromPoint((*ent).s.origin2.as_mut_ptr(),
                                                                                                               frame,
                                                                                                               eNums,
                                                                                                               crate::src::qcommon::q_shared::qtrue);
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        e += 1
        // not visible
    }
}
/*
=============
SV_BuildClientSnapshot

Decides which entities are going to be visible to the client, and
copies off the playerstate and areabits.

This properly handles multiple recursive portals, but the render
currently doesn't.

For viewing through other player's eyes, clent can be something other than client->gentity
=============
*/

unsafe extern "C" fn SV_BuildClientSnapshot(mut client: *mut crate::server_h::client_t) {
    let mut org: crate::src::qcommon::q_shared::vec3_t = [0.; 3];
    let mut frame: *mut crate::server_h::clientSnapshot_t =
        0 as *mut crate::server_h::clientSnapshot_t;
    let mut entityNumbers: snapshotEntityNumbers_t = snapshotEntityNumbers_t {
        numSnapshotEntities: 0,
        snapshotEntities: [0; 256],
    };
    let mut i: i32 = 0;
    let mut ent: *mut crate::g_public_h::sharedEntity_t =
        0 as *mut crate::g_public_h::sharedEntity_t;
    let mut state: *mut crate::src::qcommon::q_shared::entityState_t =
        0 as *mut crate::src::qcommon::q_shared::entityState_t;
    let mut svEnt: *mut crate::server_h::svEntity_t = 0 as *mut crate::server_h::svEntity_t;
    let mut clent: *mut crate::g_public_h::sharedEntity_t =
        0 as *mut crate::g_public_h::sharedEntity_t;
    let mut clientNum: i32 = 0;
    let mut ps: *mut crate::src::qcommon::q_shared::playerState_t =
        0 as *mut crate::src::qcommon::q_shared::playerState_t;
    // bump the counter used to prevent double adding
    crate::src::server::sv_main::sv.snapshotCounter += 1;
    // this is the frame we are creating
    frame = &mut *(*client)
        .frames
        .as_mut_ptr()
        .offset(((*client).netchan.outgoingSequence & 32 as i32 - 1 as i32) as isize)
        as *mut crate::server_h::clientSnapshot_t;
    // clear everything in this snapshot
    entityNumbers.numSnapshotEntities = 0 as i32;
    crate::stdlib::memset(
        (*frame).areabits.as_mut_ptr() as *mut libc::c_void,
        0 as i32,
        ::std::mem::size_of::<[crate::src::qcommon::q_shared::byte; 32]>() as libc::c_ulong,
    );
    // https://zerowing.idsoftware.com/bugzilla/show_bug.cgi?id=62
    (*frame).num_entities = 0 as i32;
    clent = (*client).gentity;
    if clent.is_null() || (*client).state as u32 == crate::server_h::CS_ZOMBIE as i32 as u32 {
        return;
    }
    // grab the current playerState_t
    ps = crate::src::server::sv_game::SV_GameClientNum(
        client.offset_from(crate::src::server::sv_main::svs.clients) as isize as i32,
    ) as *mut crate::src::qcommon::q_shared::playerState_s;
    (*frame).ps = *ps;
    // never send client's own entity, because it can
    // be regenerated from the playerstate
    clientNum = (*frame).ps.clientNum;
    if clientNum < 0 as i32 || clientNum >= (1 as i32) << 10 as i32 {
        crate::src::qcommon::common::Com_Error(
            crate::src::qcommon::q_shared::ERR_DROP as i32,
            b"SV_SvEntityForGentity: bad gEnt\x00" as *const u8 as *const libc::c_char,
        );
    }
    svEnt = &mut *crate::src::server::sv_main::sv
        .svEntities
        .as_mut_ptr()
        .offset(clientNum as isize) as *mut crate::server_h::svEntity_t;
    (*svEnt).snapshotCounter = crate::src::server::sv_main::sv.snapshotCounter;
    // find the client's viewpoint
    org[0 as i32 as usize] = (*ps).origin[0 as i32 as usize];
    org[1 as i32 as usize] = (*ps).origin[1 as i32 as usize];
    org[2 as i32 as usize] = (*ps).origin[2 as i32 as usize];
    org[2 as i32 as usize] += (*ps).viewheight as f32;
    // add all the entities directly visible to the eye, which
    // may include portal entities that merge other viewpoints
    SV_AddEntitiesVisibleFromPoint(
        org.as_mut_ptr(),
        frame,
        &mut entityNumbers,
        crate::src::qcommon::q_shared::qfalse,
    );
    // if there were portals visible, there may be out of order entities
    // in the list which will need to be resorted for the delta compression
    // to work correctly.  This also catches the error condition
    // of an entity being included twice.
    crate::stdlib::qsort(
        entityNumbers.snapshotEntities.as_mut_ptr() as *mut libc::c_void,
        entityNumbers.numSnapshotEntities as crate::stddef_h::size_t,
        ::std::mem::size_of::<i32>() as libc::c_ulong,
        Some(
            SV_QsortEntityNumbers
                as unsafe extern "C" fn(_: *const libc::c_void, _: *const libc::c_void) -> i32,
        ),
    );
    // now that all viewpoint's areabits have been OR'd together, invert
    // all of them to make it a mask vector, which is what the renderer wants
    i = 0 as i32;
    while i < 32 as i32 / 4 as i32 {
        *((*frame).areabits.as_mut_ptr() as *mut i32).offset(i as isize) =
            *((*frame).areabits.as_mut_ptr() as *mut i32).offset(i as isize) ^ -(1 as i32);
        i += 1
    }
    // copy the entity states out
    (*frame).num_entities = 0 as i32;
    (*frame).first_entity = crate::src::server::sv_main::svs.nextSnapshotEntities;
    i = 0 as i32;
    while i < entityNumbers.numSnapshotEntities {
        ent = crate::src::server::sv_game::SV_GentityNum(entityNumbers.snapshotEntities[i as usize])
            as *mut crate::g_public_h::sharedEntity_t;
        state = &mut *crate::src::server::sv_main::svs.snapshotEntities.offset(
            (crate::src::server::sv_main::svs.nextSnapshotEntities
                % crate::src::server::sv_main::svs.numSnapshotEntities) as isize,
        ) as *mut crate::src::qcommon::q_shared::entityState_t;
        *state = (*ent).s;
        crate::src::server::sv_main::svs.nextSnapshotEntities += 1;
        // this should never hit, map should always be restarted first in SV_Frame
        if crate::src::server::sv_main::svs.nextSnapshotEntities >= 0x7ffffffe as i32 {
            crate::src::qcommon::common::Com_Error(
                crate::src::qcommon::q_shared::ERR_FATAL as i32,
                b"svs.nextSnapshotEntities wrapped\x00" as *const u8 as *const libc::c_char,
            );
        }
        (*frame).num_entities += 1;
        i += 1
    }
}
/*
==================
SV_WriteVoipToClient

Check to see if there is any VoIP queued for a client, and send if there is.
==================
*/

unsafe extern "C" fn SV_WriteVoipToClient(
    mut cl: *mut crate::server_h::client_t,
    mut msg: *mut crate::qcommon_h::msg_t,
) {
    let mut totalbytes: i32 = 0 as i32;
    let mut i: i32 = 0;
    let mut packet: *mut crate::server_h::voipServerPacket_t =
        0 as *mut crate::server_h::voipServerPacket_t;
    if (*cl).queuedVoipPackets != 0 {
        // Write as many VoIP packets as we reasonably can...
        i = 0 as i32;
        while i < (*cl).queuedVoipPackets {
            packet = (*cl).voipPacket[((i + (*cl).queuedVoipIndex) as libc::c_ulong).wrapping_rem(
                (::std::mem::size_of::<[*mut crate::server_h::voipServerPacket_t; 64]>()
                    as libc::c_ulong)
                    .wrapping_div(
                        ::std::mem::size_of::<*mut crate::server_h::voipServerPacket_t>()
                            as libc::c_ulong,
                    ),
            ) as usize];
            if *(*cl).downloadName.as_mut_ptr() == 0 {
                totalbytes += (*packet).len;
                if totalbytes > ((*msg).maxsize - (*msg).cursize) / 2 as i32 {
                    break;
                }
                crate::src::qcommon::msg::MSG_WriteByte(
                    msg as *mut crate::qcommon_h::msg_t,
                    crate::qcommon_h::svc_voipOpus as i32,
                );
                crate::src::qcommon::msg::MSG_WriteShort(
                    msg as *mut crate::qcommon_h::msg_t,
                    (*packet).sender,
                );
                crate::src::qcommon::msg::MSG_WriteByte(
                    msg as *mut crate::qcommon_h::msg_t,
                    (*packet).generation as crate::src::qcommon::q_shared::byte as i32,
                );
                crate::src::qcommon::msg::MSG_WriteLong(
                    msg as *mut crate::qcommon_h::msg_t,
                    (*packet).sequence,
                );
                crate::src::qcommon::msg::MSG_WriteByte(
                    msg as *mut crate::qcommon_h::msg_t,
                    (*packet).frames,
                );
                crate::src::qcommon::msg::MSG_WriteShort(
                    msg as *mut crate::qcommon_h::msg_t,
                    (*packet).len,
                );
                crate::src::qcommon::msg::MSG_WriteBits(
                    msg as *mut crate::qcommon_h::msg_t,
                    (*packet).flags,
                    2 as i32,
                );
                crate::src::qcommon::msg::MSG_WriteData(
                    msg as *mut crate::qcommon_h::msg_t,
                    (*packet).data.as_mut_ptr() as *const libc::c_void,
                    (*packet).len,
                );
            }
            crate::src::qcommon::common::Z_Free(packet as *mut libc::c_void);
            i += 1
        }
        (*cl).queuedVoipPackets -= i;
        (*cl).queuedVoipIndex += i;
        (*cl).queuedVoipIndex = ((*cl).queuedVoipIndex as libc::c_ulong).wrapping_rem(
            (::std::mem::size_of::<[*mut crate::server_h::voipServerPacket_t; 64]>()
                as libc::c_ulong)
                .wrapping_div(
                    ::std::mem::size_of::<*mut crate::server_h::voipServerPacket_t>()
                        as libc::c_ulong,
                ),
        ) as i32 as i32
    };
}
/*
=======================
SV_SendMessageToClient

Called by SV_SendClientSnapshot and SV_SendClientGameState
=======================
*/
#[no_mangle]

pub unsafe extern "C" fn SV_SendMessageToClient(
    mut msg: *mut crate::qcommon_h::msg_t,
    mut client: *mut crate::server_h::client_t,
) {
    // record information about the message
    (*client).frames[((*client).netchan.outgoingSequence & 32 as i32 - 1 as i32) as usize]
        .messageSize = (*msg).cursize;
    (*client).frames[((*client).netchan.outgoingSequence & 32 as i32 - 1 as i32) as usize]
        .messageSent = crate::src::server::sv_main::svs.time;
    (*client).frames[((*client).netchan.outgoingSequence & 32 as i32 - 1 as i32) as usize]
        .messageAcked = -(1 as i32);
    // send the datagram
    crate::src::server::sv_net_chan::SV_Netchan_Transmit(
        client as *mut crate::server_h::client_s,
        msg as *mut crate::qcommon_h::msg_t,
    );
}
/*
=======================
SV_SendClientSnapshot

Also called by SV_FinalMessage

=======================
*/
#[no_mangle]

pub unsafe extern "C" fn SV_SendClientSnapshot(mut client: *mut crate::server_h::client_t) {
    let mut msg_buf: [crate::src::qcommon::q_shared::byte; 16384] = [0; 16384];
    let mut msg: crate::qcommon_h::msg_t = crate::qcommon_h::msg_t {
        allowoverflow: crate::src::qcommon::q_shared::qfalse,
        overflowed: crate::src::qcommon::q_shared::qfalse,
        oob: crate::src::qcommon::q_shared::qfalse,
        data: 0 as *mut crate::src::qcommon::q_shared::byte,
        maxsize: 0,
        cursize: 0,
        readcount: 0,
        bit: 0,
    };
    // build the snapshot
    SV_BuildClientSnapshot(client);
    // bots need to have their snapshots build, but
    // the query them directly without needing to be sent
    if !(*client).gentity.is_null() && (*(*client).gentity).r.svFlags & 0x8 as i32 != 0 {
        return;
    }
    crate::src::qcommon::msg::MSG_Init(
        &mut msg as *mut _ as *mut crate::qcommon_h::msg_t,
        msg_buf.as_mut_ptr(),
        ::std::mem::size_of::<[crate::src::qcommon::q_shared::byte; 16384]>() as libc::c_ulong
            as i32,
    );
    msg.allowoverflow = crate::src::qcommon::q_shared::qtrue;
    // NOTE, MRE: all server->client messages now acknowledge
    // let the client know which reliable clientCommands we have received
    crate::src::qcommon::msg::MSG_WriteLong(
        &mut msg as *mut _ as *mut crate::qcommon_h::msg_t,
        (*client).lastClientCommand,
    );
    // (re)send any reliable server commands
    SV_UpdateServerCommandsToClient(client, &mut msg);
    // send over all the relevant entityState_t
    // and the playerState_t
    SV_WriteSnapshotToClient(client, &mut msg);
    SV_WriteVoipToClient(client, &mut msg);
    // check for overflow
    if msg.overflowed as u64 != 0 {
        crate::src::qcommon::common::Com_Printf(
            b"WARNING: msg overflowed for %s\n\x00" as *const u8 as *const libc::c_char,
            (*client).name.as_mut_ptr(),
        );
        crate::src::qcommon::msg::MSG_Clear(&mut msg as *mut _ as *mut crate::qcommon_h::msg_t);
    }
    SV_SendMessageToClient(&mut msg, client);
}
/*
===========================================================================
Copyright (C) 1999-2005 Id Software, Inc.

This file is part of Quake III Arena source code.

Quake III Arena source code is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

Quake III Arena source code is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Quake III Arena source code; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
===========================================================================
*/
// server.h
//=============================================================================
// !!! MUST NOT CHANGE, SERVER AND
// GAME BOTH REFERENCE !!!
// for delta compression of initial sighting
// if -1, use headnode instead
// if all the clusters don't fit in clusternums
// used to prevent double adding from portal views
// no map loaded
// spawning level entities
// actively running
// if true, send configstring changes during SS_LOADING
// changes each server start
// serverId before a map_restart
// the feed key that we use to compute the pure checksum strings
// https://zerowing.idsoftware.com/bugzilla/show_bug.cgi?id=475
// the serverId associated with the current checksumFeed (always <= serverId)
// incremented for each snapshot built
// <= 1000 / sv_frame->value
// when time > nextFrameTime, process world
// used during game VM init
// the game virtual machine will update these on init and changes
// current number, <= MAX_GENTITIES
// will be > sizeof(playerState_t) due to game private data
// portalarea visibility bits
// into the circular sv_packet_entities[]
// the entities MUST be in increasing state number
// order, otherwise the delta compression will fail
// time the message was transmitted
// time the message was acked
// used to rate drop packets
// can be reused for a new connection
// client has been disconnected, but don't reuse
// connection for a couple seconds
// has been assigned to a client_t, but no gamestate yet
// gamestate has been sent, but client hasn't sent a usercmd
// client is fully in game
// valid command string for SV_Netchan_Encode
// name, etc
// last added reliable message, not necessarily sent or acknowledged yet
// last acknowledged reliable message
// last sent reliable message, not necessarily acknowledged yet
// netchan->outgoingSequence of gamestate
// for delta compression
// reliable client message sequence
// SV_GentityNum(clientnum)
// extracted from userinfo, high bits masked
// downloading
// if not empty string, we are downloading
// file being downloaded
// total bytes (can't use EOF because of paks)
// bytes sent
// last block we sent to the client, awaiting ack
// current block number
// last block we xmited
// the buffers for the download blocks
// We have sent the EOF block
// time we last got an ack from the client
// frame last client usercmd message
// svs.time when another reliable command will be allowed
// svs.time when packet was last received
// svs.time when connection started
// svs.time of last sent snapshot
// true if nextSnapshotTime was set based on rate instead of snapshotMsec
// must timeout a few frames in a row so debugging doesn't break
// updates can be delta'd from here
// bytes / second
// requests a snapshot every snapshotMsec unless rate choked
// TTimo - additional flag to distinguish between a bad pure checksum, and no cp command at all
// TTimo
// queuing outgoing fragmented messages to send them properly, without udp packet bursts
// in case large fragmented messages are stacking up
// buffer them into this queue, and hand them out to netchan as needed
//=============================================================================
// MAX_CHALLENGES is made large to prevent a denial
// of service attack that could cycle all of them
// out before legitimate users connected
// Allow a certain amount of challenges to have the same IP address
// to make it a bit harder to DOS one single IP address from connecting
// while not allowing a single ip to grab all challenge resources
// challenge number coming from the client
// time the last packet was sent to the autherize server
// time the challenge response was sent to client
// time the adr was first used, for authorize timeout checks
// this structure will be cleared only when the game dll changes
// sv_init has completed
// will be strictly increasing across level changes
// ^= SNAPFLAG_SERVERCOUNT every SV_SpawnServer()
// [sv_maxclients->integer];
// sv_maxclients->integer*PACKET_BACKUP*MAX_SNAPSHOT_ENTITIES
// next snapshotEntities to use
// [numSnapshotEntities]
// to prevent invalid IPs from connecting
// for rcon return messages
// authorize server address
// next svs.time that server should do dns lookup for master server
// Structure for managing bans
// For a CIDR-Notation type suffix
//=============================================================================
// persistant server info across maps
// cleared each map
// game virtual machine
//===========================================================
//
// sv_main.c
//
//
// sv_init.c
//
//
// sv_client.c
//
//
// sv_ccmds.c
//
//
// sv_snapshot.c
//
/*
=======================
SV_SendClientMessages
=======================
*/
#[no_mangle]

pub unsafe extern "C" fn SV_SendClientMessages() {
    let mut i: i32 = 0;
    let mut c: *mut crate::server_h::client_t = 0 as *mut crate::server_h::client_t;
    let mut current_block_6: u64;
    // send a message to each connected client
    i = 0 as i32; // not connected
    while i < (*crate::src::server::sv_main::sv_maxclients).integer {
        c = &mut *crate::src::server::sv_main::svs.clients.offset(i as isize)
            as *mut crate::server_h::client_t; // It's not time yet
        if !((*c).state as u64 == 0) {
            if !(((crate::src::server::sv_main::svs.time - (*c).lastSnapshotTime) as f32)
                < (*c).snapshotMsec as f32 * (*crate::src::qcommon::common::com_timescale).value)
            {
                if !(*(*c).downloadName.as_mut_ptr() != 0) {
                    if (*c).netchan.unsentFragments as u32 != 0
                        || !(*c).netchan_start_queue.is_null()
                    {
                        (*c).rateDelayed = crate::src::qcommon::q_shared::qtrue // Client is downloading, don't send snapshots
                                                                                // Drop this snapshot if the packet queue is still full or delta compression will break
                    } else {
                        if !((*c).netchan.remoteAddress.type_0 as u32
                            == crate::qcommon_h::NA_LOOPBACK as i32 as u32
                            || (*crate::src::server::sv_main::sv_lanForceRate).integer != 0
                                && crate::src::qcommon::net_ip::Sys_IsLANAddress(
                                    (*c).netchan.remoteAddress as crate::qcommon_h::netadr_t,
                                ) as u32
                                    != 0)
                        {
                            // rate control for clients not on LAN
                            if crate::src::server::sv_main::SV_RateMsec(
                                c as *mut crate::server_h::client_s,
                            ) > 0 as i32
                            {
                                // Not enough time since last packet passed through the line
                                (*c).rateDelayed = crate::src::qcommon::q_shared::qtrue;
                                current_block_6 = 16559507199688588974;
                            } else {
                                current_block_6 = 12599329904712511516;
                            }
                        } else {
                            current_block_6 = 12599329904712511516;
                        }
                        match current_block_6 {
                            16559507199688588974 => {}
                            _ => {
                                // generate and send a new message
                                SV_SendClientSnapshot(c);
                                (*c).lastSnapshotTime = crate::src::server::sv_main::svs.time;
                                (*c).rateDelayed = crate::src::qcommon::q_shared::qfalse
                            }
                        }
                    }
                }
            }
        }
        i += 1
    }
}
